import type { GetStaticProps, NextPage } from 'next';
import Image from 'next/image';
import Page from '../components/Page';
import Confetti from '../components/Confetti';
import styles from '../styles/Home.module.scss';

interface IRootProps {
  enableConfetti: boolean;
}

const Index: NextPage<IRootProps> = ({ enableConfetti }) => {
  return (
    <Page title="Juliette Cordor" description="Generated by Create Next Stack.">
      {enableConfetti && <Confetti />}
      <main className={styles.container}>
        <Image
          src="https://avatars.githubusercontent.com/u/61040004"
          width="200px"
          height="200px"
          alt="My Github profile picture"
          className={styles.pfp}
        />
        <h1>Welcome to my profile!</h1>
        <h2>
          My name is <span>Juliette Cordor</span> and my pronouns are{' '}
          <span>She/Her</span>
        </h2>

        <Image
          src="https://raw.githubusercontent.com/jewlexx/jewlexx/main/github-metrics.svg"
          width="480px"
          height="419px"
          alt="My Github Statistics"
          className={styles.stats}
        />
      </main>
    </Page>
  );
};

export const getStaticProps: GetStaticProps<IRootProps> = () => {
  const isProduction = process.env.NODE_ENV === 'production';

  return {
    props: {
      enableConfetti: isProduction,
    },
  };
};

export default Index;
