import type { GetStaticProps, NextPage } from 'next';
import Page from 'components/Page';
import PFP from 'components/PFP';
import useConfetti from 'components/Confetti';
import Stats from 'components/Stats';
import styles from 'styles/Home.module.scss';

interface IRootProps {
  enableConfetti: boolean;
}

const Index: NextPage<IRootProps> = ({ enableConfetti }) => {
  useConfetti(enableConfetti);
  return (
    <Page title="Juliette Cordor" description="Generated by Create Next Stack.">
      <main className={styles.container}>
        <PFP />

        <h1>Welcome to my profile!</h1>
        <h2>
          My name is <span>Juliette Cordor</span> and my pronouns are{' '}
          <span>She/Her</span>
        </h2>
        <desc>
          Note: If you are here from something related to my legal identity, eg.
          a job, my legal name is James Grasso, as I have not yet changed it
        </desc>

        <Stats />
      </main>
    </Page>
  );
};

export const getStaticProps: GetStaticProps<IRootProps> = () => {
  const isProduction = process.env.NODE_ENV === 'production';

  return {
    props: {
      enableConfetti: isProduction,
    },
  };
};

export default Index;
